project/main/forms.py
from wtforms import StringField, TextAreaField, SelectField, validators, SubmitField
from flask_wtf import FlaskForm

class ContactForm(FlaskForm):
    
    name = StringField('Name', [validators.DataRequired()])
    email = StringField(
        'Email', [validators.DataRequired(), validators.Email()])
    subject = StringField('Subject', [validators.DataRequired()])
    message = TextAreaField('Message', [validators.Length(min=1, max=300)])
    submit = SubmitField('Send')

project/projects/forms.py
from wtforms import StringField, TextAreaField, SelectField, validators, SubmitField
from flask_wtf import FlaskForm

class ProjectForm(FlaskForm):
    title = StringField('Title', [validators.DataRequired()])
    description = StringField('Description', [validators.Length(min=1, max=250)])
    category = SelectField('Category', [validators.DataRequired()],
                            choices=[('convergence behaviour','convergence behaviour'), 
                                    ('response','response'),
                                     ],
                            )
    submit = SubmitField('Create')
    
    

project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, \
    PasswordField, SelectField, validators, ValidationError, SubmitField
    

from flask_login import current_user

from project.models import User


class RegisterForm(FlaskForm):
    name = StringField('Name', [validators.Length(min=1, max=25)])
    username = StringField('Username', [validators.Length(min=4, max=25)])
    email = StringField('Email', [validators.Length(min=6, max=25),
                                  validators.Email()
                                  ])
    password = PasswordField('Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm_password',
                           message='Passwords do not match')
    ])
    confirm_password = PasswordField('Confirm Password')
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError(
                'That username is taken. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError(
                'That email is taken. Please choose a different one.')


class LoginForm(FlaskForm):

    email = StringField(
        'Email', [validators.DataRequired(), validators.Email()])
    password = PasswordField('Password', [validators.DataRequired()])
    submit = SubmitField('Login')


class UpdateAccountForm(FlaskForm):
    name = StringField('Name', [validators.Length(min=1, max=25)])
    username = StringField('Username', [validators.Length(min=4, max=25)])
    email = StringField('Email', [validators.Length(min=6, max=25)])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError(
                    'That username is taken. Please choose a different one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError(
                    'That email is taken. Please choose a different one.')


class RequestResetForm(FlaskForm):
    email = StringField('Email', [validators.Length(min=6, max=25),
                                  validators.Email()
                                  ])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError(
                'There is no account with that email. You must register first.')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', [
                                validators.DataRequired(),
                                validators.EqualTo('confirm_password',
                                                message='Passwords do not match')
                                                    ])
    confirm_password = PasswordField('Confirm Password')
    submit = SubmitField('Reset Password')

project/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_admin import Admin
from flask_mail import Mail
import os
# from project.config import DevelopmentConfig

server = Flask(__name__)
# server.config.from_object(DevelopmentConfig)
server.config.from_object('config.ProductionConfig')


db = SQLAlchemy(server, session_options={
    'expire_on_commit': False
})



login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'
login_manager.init_app(server)

admin = Admin(server)

mail = Mail()
mail.init_app(server)

from .models import User
@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()

from .admin import *

###dash apps

# from werkzeug.middleware.dispatcher import DispatcherMiddleware
from .convergence_dash_app import conv_dash_app
from .response_dash_app import resp_dash_app


# app_dash = DispatcherMiddleware(server, {
#     '/dash': dash_app1.server
#     # '/app2': dash_app2.server,
# })

from project.users.routes import users
from project.projects.routes import projects
from project.main.routes import main

server.register_blueprint(users)
server.register_blueprint(projects)
server.register_blueprint(main)

# from project import routes

project/main/routes.py
from flask import Flask, render_template, redirect, Blueprint, request
from project import mail
from flask_mail import Message
from flask_login import login_required
from .forms import ContactForm
main = Blueprint('main', __name__)



@main.route('/')
def index():
    return render_template('home.html')

@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            msg = Message(form.subject.data, 
                          sender='maciek.kraczla@gmail.com', 
                          recipients=['maciek.kraczla@gmail.com'])
            msg.body = f"""
            From: {form.name.data} &lt;{form.email.data}&gt;
            {form.message.data}
            """
            mail.send(msg)
        
            return render_template('contact.html', success=True)
            
    if request.method == 'GET':
        return render_template('contact.html', form=form)
    

@main.route('/docs')
def docs():
    return render_template('docs.html')

project/projects/routes.py
from flask import Flask, request, render_template, flash, \
                 redirect, url_for, session, logging, abort, Blueprint
from flask_login import current_user, login_required
from project.projects.forms import ProjectForm
from project.models import *

projects = Blueprint('projects', __name__)

@projects.route('/projects')
@login_required
def projects_all():
    username = current_user.username
    user = User.query.filter_by(username=username).first()
    user_projects = user.projects
    return render_template('projects.html', projects=user_projects)


# @projects.route('/convergence/')
# @login_required
# def render_chart():
#     pass
#     # return redirect('/dash')
    
@projects.route('/rendering/')
def render_chart():
    project_id = session["project_id"]
    project = Project.query.filter_by(id=project_id).first()
    category = project.category
    if category == 'convergence behaviour':
        return redirect('/convergence')
    elif category == 'response':
        return redirect('/response')
    else:
        return redirect(url_for('projects.project', project_id=project_id))
    # return redirect('/dash')

@projects.route('/projects/<int:project_id>/render')
@login_required
def render_project(project_id):
    # project = Project.query.filter_by(id=project_id).first()
    session["project_id"] = project_id
    return redirect(url_for('projects.render_chart'))


@projects.route('/projects/<int:project_id>/')
@login_required
def project(project_id):
    project = Project.query.filter_by(id=project_id).first()
    return render_template('project.html', project=project)


@projects.route('/projects/new', methods=['GET', 'POST'])
@login_required
def add_project():
    form = ProjectForm(request.form)
    if request.method == 'POST' and form.validate():
        project = Project(
            title=form.title.data,
            description=form.description.data,
            author_id = current_user.id,
            category=form.category.data
        )
        
        db.session.add(project)
        
        results = Result(project)
        db.session.add(results)
        
        user = User.query.filter_by(username=current_user.username).first()
        user.projects.append(project)
        
        db.session.commit()
        print(user.projects)
        flash('You successfully added a project.', 'success')
        return redirect(url_for('projects.projects_all'))
    return render_template('add_project.html', form=form,
                             title="New project", legend="New project")


@projects.route('/projects/<int:project_id>/update', methods=['GET', 'POST'])
@login_required
def update_project(project_id):
    project = Project.query.get_or_404(project_id)
    if project.author_id != current_user.id:
        abort(403)
    form = ProjectForm()
    form.category.choices = [project.category]
    if form.validate_on_submit():
        project.title = form.title.data
        project.description = form.description.data
        project.category = form.category.data
        #if more categories are added; changing category implies ereasing data from DB.
        db.session.commit()
        flash('Your project has been updated!', 'success')
        return redirect(url_for('projects.project', project_id=project_id))
    elif request.method == 'GET':
        form.title.data = project.title
        form.description.data = project.description
        form.category.data = project.category
        
    return render_template('add_project.html', form=form, 
                           title="Update project", legend="Update project") 
    

@projects.route('/projects/<int:project_id>/delete', methods=['GET','POST'])
@login_required
def delete_project(project_id):
    project = Project.query.get_or_404(project_id)
    if project.author_id != current_user.id:
        abort(403)
    
    db.session.delete(project)
    db.session.commit()
    flash('Your project has been deleted.', 'success')
    return redirect(url_for('projects.projects_all'))

project/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from passlib.hash import sha256_crypt

from project import db
from project.models import *
from project.users.forms import LoginForm, RegisterForm, UpdateAccountForm,\
                                RequestResetForm, ResetPasswordForm
                                
from project.users.utils import send_reset_email

users = Blueprint('users', __name__)

@users.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if request.method == 'POST' and form.validate_on_submit():
        default_role = Role.query.filter_by(name='user').first()
        user = User(
            name=form.name.data,
            email=form.email.data,
            username=form.username.data,
            password=form.password.data,
            roles= [default_role, ]
        )
        db.session.add(user)
        db.session.commit()
        flash('You are successfully registered.', 'success')
        # login_user(user)
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        print(current_user.name)
        return redirect(url_for('main.index'))
    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and sha256_crypt.verify(form.password.data, user.password):
                login_user(user)
                next_page = request.args.get('next')
                flash('You are logged in', 'success')
                return redirect(next_page) if next_page else redirect(url_for('main.index'))
            else:
                flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You are successfully logged out', 'success')
    return redirect(url_for('users.login'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.name.data = current_user.name
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)



@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        password = sha256_crypt.encrypt(str(form.password.data))
        user.password = password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route('/delete', methods=['GET','POST'])
@login_required
def delete_account():
    if current_user.is_authenticated:
        db.session.delete(current_user)
        db.session.commit()
        flash('Your account has been deleted.', 'success')
        return redirect(url_for('users.login'))

project/templates/about.html
{% extends 'base.html' %}

{% block content %}
<div>
  <legend class="border-bottom mb-4">About</legend>
  <p>Under construction. More information coming soon.</p>
</div>
{% endblock %}

project/templates/account.html
{% extends 'base.html' %}

{% block content %}
<div class="content-section">
    <div class="media">
        <div class="media-body">
            <h3 class="account-heading">{{ current_user.username }}</h3>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                {{ form.name(class="form-control form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.name.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.name(class="form-control form-control") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info btn-sm") }}
            <button type="button" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#deleteModal">
                Delete
            </button>
        </div>
    </form>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete your account?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('users.delete_account') }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

project/templates/add_project.html
{% extends 'base.html' %}

{% block content %}

<legend class="border-bottom mb-4">{{legend}}</legend>

<form method="POST" action="">
  {{ form.hidden_tag() }}
  <fieldset class="form-group">
    <div class="form-group">
      {{ form.title.label(class="form-control-label") }}

      {% if form.title.errors %}
      {{ form.title(class="form-control form-control is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.title.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %}
      {{ form.title(class="form-control form-control ") }}
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.description.label(class="form-control-label") }}

      {% if form.description.errors %}
      {{ form.description(class="form-control form-control is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.description.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %}
      {{ form.description(class="form-control form-control ") }}
      {% endif %}
    </div>

    <div class="form-group">
      {{ form.category.label(class="form-control-label") }}
      {% if form.category.errors %}
      {{ form.category(class="form-control form-control  is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.category.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %}
      {{ form.category(class="form-control form-control ") }}
      {% endif %}
    </div>
  </fieldset>
  <div class="form-group">
    {{ form.submit(class="btn btn-primary btn-sm mx-1") }}

    <a href="{{url_for('projects.projects_all')}}" class="btn btn-primary btn-sm mx-1">
      Back
    </a>
  </div>
</form>
</div>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

  {% if title %}
  <title>{{ title }}</title>
  {% else %}
  <title>Projects</title>
  {% endif %}


</head>

<body>

  <header class="site-header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-color">
      <div class="container">
        <a class="navbar-brand mr-4" href="{{ url_for('main.index') }}">Projects</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About</a>
            </li>

            <!-- <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.docs')}}">Docs</a>
            </li> -->
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.contact')}}">Contact</a>
            </li>



          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('projects.projects_all') }}">My projects</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/account">My account</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/logout">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="/register">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            {% endif %}
          </ul>

        </div>
      </div>
    </nav>
  </header>

  <div class="container">
    {% include 'includes/_messages.html'%}
    {% block content %}{% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

project/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<div>
    <legend class="border-bottom mb-4">Contact</legend>


    {% if success %}
    <p>Your message has been sent. Thank you.</p>
    {% else %}
    <p>Do you have questions or remarks? Feel free to contact us. </p>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group col-md-6 px-0">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                {{ form.name(class="form-control form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.name.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.name(class="form-control form-control") }}
                {% endif %}

            </div>
            <div class="form-group col-md-6 px-0">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control") }}
                {% endif %}
            </div>
            <div class="form-group col-md-6 px-0">
                {{ form.subject.label(class="form-control-label") }}
                {% if form.subject.errors %}
                {{ form.subject(class="form-control form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.subject.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.subject(class="form-control form-control") }}
                {% endif %}
            </div>
            <div class="form-group col-md-8 px-0">
                {{ form.message.label(class="form-control-label") }}
                {% if form.message.errors %}
                {{ form.message(class="form-control form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.message.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.message(class="form-control form-control") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    {% endif %}
</div>
{% endblock %}

project/templates/docs.html
{% extends 'base.html' %}

{% block content %}
<div>
    <legend class="border-bottom mb-4">Docs</legend>
    <p>Under construction. More information coming soon.</p>
</div>
{% endblock %}

project/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="">
  <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4">Log In</legend>
          <div class="form-group col-md-6 px-0">
              {{ form.email.label(class="form-control-label") }}
              {% if form.email.errors %}
                  {{ form.email(class="form-control form-control is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.email(class="form-control form-control") }}
              {% endif %}
          </div>
          <div class="form-group col-md-6 px-0">
              {{ form.password.label(class="form-control-label") }}
              {% if form.password.errors %}
                  {{ form.password(class="form-control form-control is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.password.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.password(class="form-control form-control") }}
              {% endif %}
          </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
        <small class="text-muted ml-2">
            <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
        </small>
    </div>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
      Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
  </small>
</div>
{% endblock %}

project/templates/project.html
{% extends 'base.html' %}

{% block content %}
<div>
    <div class="card">
        <div class="card-header">
            <legend class="border-bottom mb-4">{{project.title}}</legend>
            <small>Created on: {{project.create_date.strftime('%Y-%m-%d')}}</small>
        </div>
        <div class="card-body">
            <p class="card-text">{{project.description}}</p>
            <div class="row py-2">
                <div class="col">
                    <a href="{{ url_for('projects.render_project', project_id=project.id)}}"
                        class="btn btn-outline-info btn-sm mx-1">
                        Results
                    </a>
                    <a href="{{url_for('projects.update_project', project_id=project.id)}}"
                        class="btn btn-outline-info btn-sm mx-1">
                        Update
                    </a>
                    <button type="button" class="btn  btn-outline-danger btn-sm mx-1 float-right" data-toggle="modal"
                        data-target="#deleteModal">
                        Delete
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Project?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
                <form action="{{ url_for('projects.delete_project', project_id=project.id) }}" method="POST">
                    <input class="btn btn-danger btn-sm" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}